python train.py \
    --model_type "conv" \
    --output_directory "models/run0" \
    --dataset_directory "../data/prepare/trigger/" \
    --batch_size 64 \
    --num_workers 10 \
    --num_epochs 100 \
    --transforms "bandpass:whiten" \
    --augmentations "amplitude:noise" \
    --length 8192 \
    --sample_strategy "sequential" \
    --learning_rate 2e-5 \
    --weight_decay 1e-1 \
    --split SAC_20030927_XF_prem \
    --embedding_size 10 \
    --loss_function "dpcl"
